/*
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public class CalculatorScopeProvider extends DelegatingScopeProvider {
}
