/*
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.calc.parser.antlr.internal.InternalCalculatorParser;
import org.xtext.calc.services.CalculatorGrammarAccess;

public class CalculatorParser extends AbstractAntlrParser {

	@Inject
	private CalculatorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCalculatorParser createParser(XtextTokenStream stream) {
		return new InternalCalculatorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Calculation";
	}

	public CalculatorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CalculatorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
