/*
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.calc.CalculatorRuntimeModule;
import org.xtext.calc.CalculatorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CalculatorIdeSetup extends CalculatorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CalculatorRuntimeModule(), new CalculatorIdeModule()));
	}
	
}
