/**
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.webCalc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.calc.webCalc.WebCalcPackage#getDeclaredParameter()
 * @model
 * @generated
 */
public interface DeclaredParameter extends AbstractDefinition
{
} // DeclaredParameter
