/**
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.webCalc.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.calc.webCalc.DeclaredParameter;
import org.xtext.calc.webCalc.WebCalcPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declared Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeclaredParameterImpl extends AbstractDefinitionImpl implements DeclaredParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclaredParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebCalcPackage.Literals.DECLARED_PARAMETER;
  }

} //DeclaredParameterImpl
