/**
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.webCalc.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.calc.webCalc.AbstractDefinition;
import org.xtext.calc.webCalc.DeclaredParameter;
import org.xtext.calc.webCalc.Definition;
import org.xtext.calc.webCalc.WebCalcPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.calc.webCalc.impl.DefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.calc.webCalc.impl.DefinitionImpl#isNative <em>Native</em>}</li>
 *   <li>{@link org.xtext.calc.webCalc.impl.DefinitionImpl#isIsFunction <em>Is Function</em>}</li>
 *   <li>{@link org.xtext.calc.webCalc.impl.DefinitionImpl#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefinitionImpl extends StatementImpl implements Definition
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isNative() <em>Native</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNative()
   * @generated
   * @ordered
   */
  protected static final boolean NATIVE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNative() <em>Native</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNative()
   * @generated
   * @ordered
   */
  protected boolean native_ = NATIVE_EDEFAULT;

  /**
   * The default value of the '{@link #isIsFunction() <em>Is Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsFunction()
   * @generated
   * @ordered
   */
  protected static final boolean IS_FUNCTION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsFunction() <em>Is Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsFunction()
   * @generated
   * @ordered
   */
  protected boolean isFunction = IS_FUNCTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<DeclaredParameter> params;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebCalcPackage.Literals.DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebCalcPackage.DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isNative()
  {
    return native_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNative(boolean newNative)
  {
    boolean oldNative = native_;
    native_ = newNative;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebCalcPackage.DEFINITION__NATIVE, oldNative, native_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsFunction()
  {
    return isFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsFunction(boolean newIsFunction)
  {
    boolean oldIsFunction = isFunction;
    isFunction = newIsFunction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebCalcPackage.DEFINITION__IS_FUNCTION, oldIsFunction, isFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DeclaredParameter> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<DeclaredParameter>(DeclaredParameter.class, this, WebCalcPackage.DEFINITION__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WebCalcPackage.DEFINITION__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WebCalcPackage.DEFINITION__NAME:
        return getName();
      case WebCalcPackage.DEFINITION__NATIVE:
        return isNative();
      case WebCalcPackage.DEFINITION__IS_FUNCTION:
        return isIsFunction();
      case WebCalcPackage.DEFINITION__PARAMS:
        return getParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WebCalcPackage.DEFINITION__NAME:
        setName((String)newValue);
        return;
      case WebCalcPackage.DEFINITION__NATIVE:
        setNative((Boolean)newValue);
        return;
      case WebCalcPackage.DEFINITION__IS_FUNCTION:
        setIsFunction((Boolean)newValue);
        return;
      case WebCalcPackage.DEFINITION__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends DeclaredParameter>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WebCalcPackage.DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case WebCalcPackage.DEFINITION__NATIVE:
        setNative(NATIVE_EDEFAULT);
        return;
      case WebCalcPackage.DEFINITION__IS_FUNCTION:
        setIsFunction(IS_FUNCTION_EDEFAULT);
        return;
      case WebCalcPackage.DEFINITION__PARAMS:
        getParams().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WebCalcPackage.DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case WebCalcPackage.DEFINITION__NATIVE:
        return native_ != NATIVE_EDEFAULT;
      case WebCalcPackage.DEFINITION__IS_FUNCTION:
        return isFunction != IS_FUNCTION_EDEFAULT;
      case WebCalcPackage.DEFINITION__PARAMS:
        return params != null && !params.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == AbstractDefinition.class)
    {
      switch (derivedFeatureID)
      {
        case WebCalcPackage.DEFINITION__NAME: return WebCalcPackage.ABSTRACT_DEFINITION__NAME;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == AbstractDefinition.class)
    {
      switch (baseFeatureID)
      {
        case WebCalcPackage.ABSTRACT_DEFINITION__NAME: return WebCalcPackage.DEFINITION__NAME;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", native: ");
    result.append(native_);
    result.append(", isFunction: ");
    result.append(isFunction);
    result.append(')');
    return result.toString();
  }

} //DefinitionImpl
