/**
 * generated by Xtext 2.25.0
 */
package org.xtext.calc.webCalc.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.calc.webCalc.Evaluation;
import org.xtext.calc.webCalc.WebCalcPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evaluation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EvaluationImpl extends StatementImpl implements Evaluation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvaluationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebCalcPackage.Literals.EVALUATION;
  }

} //EvaluationImpl
